In [ ]:
import numpy as np



: 

In [ ]:
arr = np.arange(24).reshape(2,3,4)
arr1 = np.arange(12).reshape(3,4)
arr2 = np.array([1,2])
arr3 = np.array([4,5])
print(arr+arr1)


[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[12 14 16 18]
  [20 22 24 26]
  [28 30 32 34]]]


# ROW AND COLOUMN VECTOR
Row vector means array with single row and multiple coulumns

and Coloumn Vector means array with single coloumn and multiple rows


# Reshape


In [ ]:
#reshape(row,col)
arr = np.arange(12).reshape(4,-1)#when we  write -1 in col the python will it self decide how many columns to take based on the elements
print(arr)
## arr2= arr.reshape(5,-1) # this gives error becuase here the dimensions are not multiples
print(arr.shape)

#remember (10,) and (10,1) are different dimensions first is 1d and the latter is 2d


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [ ]:
arr = np.arange(10)
print(arr.shape)
arr1 = arr.reshape(1,-1)# look here we used -1 to make a row vector
print("ROW VECTOR",arr1)
arr2 = arr.reshape(-1,1) # look here we used -1 to make a column vector
print("COL VECTOR",arr2)

(10,)
ROW VECTOR [[0 1 2 3 4 5 6 7 8 9]]
COL VECTOR [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
## np.newaxis - can increase dimension to higher dimensions like(1d-to-2d),(2d-to-3d),etc.
arr1 = np.arange(12)
arr1 = arr1[:,np.newaxis]
print(arr1)


: 

In [ ]:
#.ravil and .flatten
arr = np.arange(12).reshape(4,3)
print(arr)
arr1 = arr.ravel() # it make the shallow copy
arr1[0]= 99
arr2 = arr.flatten() # it makes deep copy
arr2 [2]= 100
print(arr1)
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[99  1  2  3  4  5  6  7  8  9 10 11]
[ 99   1 100   3   4   5   6   7   8   9  10  11]


In [ ]:
arr1 = np.ones(12).reshape(3,4)
arr1[0]=arr1[0]+10
arr1[1]=arr1[1]+20
arr1[2]=arr1[2]+30
print(arr1)


[[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]


In [ ]:
#np.vstack() and np.hstack()
arr1 = np.array([[1,3,4],[2,0,5]])
arr2 = np.array([[5,6,7],[8,9,10]])
arr3 = np.vstack((arr1,arr2)) # in vstack the number of col should be same and it stacks vertically
arr4 = np.hstack((arr1,arr2))# in hstack the number of rows should be same and it stacks vertically
print("vstack:",arr3)
print()
print("hstack:",arr4)

vstack: [[ 1  3  4]
 [ 2  0  5]
 [ 5  6  7]
 [ 8  9 10]]

hstack: [[ 1  3  4  5  6  7]
 [ 2  0  5  8  9 10]]


In [ ]:
#np.concatenate()with axis
# when axis -> 0  it works as vstack
# and when axis ->1 it works as hstack

np.concatenate((arr1,arr2),axis=0)

np.concatenate((arr1,arr2),axis=1)

array([[ 1,  3,  4,  5,  6,  7],
       [ 2,  0,  5,  8,  9, 10]])

In [ ]:
#np.where(condition,true_val,false_val)
arr = np.array([2,-10,20,-15,-18,10])
arr1 = np.where(arr>0,arr,0)
print(arr1)

#nested np.where()
arr2 = np.array([20, 70, 45, 24, 100, 59])
arr3 = np.where(arr2>=80,"A",np.where((60<=arr2) & (arr2<=79),"B","C"))
print(arr3)

[ 2  0 20  0  0 10]
['C' 'B' 'C' 'C' 'A' 'C']


In [ ]:
marks = np.array([35,68,91,27,55])
print(np.where(marks>50))
print(marks[np.where(marks>50)])
print(np.where(marks>50)[0])


(array([1, 2, 4]),)
[68 91 55]
[1 2 4]


In [ ]:
# dot product
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a*b",a*b)
print("np.dot",np.dot(a,b))
print("a@b", a@b)

a=np.array(([1,2,3],[4,5,6]))
#transpose
print(a.T)
print()
# to convert any matrix to square matrix multiply it too its transpose
print(a@a.T)


a*b [ 4 10 18]
np.dot 32
a@b 32
[[1 4]
 [2 5]
 [3 6]]

[[14 32]
 [32 77]]


In [ ]:
s1= [72,85,60,91]
s2= [45,38,98,55]
s3=[88,66,74,100]
s4 =np.array((s1,s2,s3))
print(s4)
print()
print(s4.shape[0],s4.shape[1])
print()

print(np.size(s4))
print()
s4.astype('float32')
old = np.array([['62', '71', '55', '80'],
                ['49', '58', '66', '73']])

print(old.astype('int32'))


[[ 72  85  60  91]
 [ 45  38  98  55]
 [ 88  66  74 100]]

3 4

12

[[62 71 55 80]
 [49 58 66 73]]


In [ ]:
print(np.vstack((s4,old)))

[['72' '85' '60' '91']
 ['45' '38' '98' '55']
 ['88' '66' '74' '100']
 ['62' '71' '55' '80']
 ['49' '58' '66' '73']]


In [ ]:
table = np.zeros(24).reshape(6,4).astype('int32')
print(table)
sheet = np.full((6,4),35)
print(sheet)
s = np.arange(101,130,2)
print(s)
print(len(s))

x = np.linspace(0,3,7)
print(x)

i = np.eye(5,dtype=int)*10
print(i)
j = np.full(4,35)
k = np.eye(4,dtype=int)*65


print(j+k)



[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
15
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]
