In [2]:
import numpy as np


In [3]:
np.array([1,2.5,"hello"])

x= np.array([1,2.5,3.66])
print(x.dtype)

float64


In [7]:
x= np.array([1,2.5,3.66,4.8,4.3])
print(x)
print(x.astype('int32'))#this does not change the original array it just creates an another array of given type



[1.   2.5  3.66 4.8  4.3 ]
[1 2 3 4 4]


In [15]:
#artihmetic  - array with scalar , array with array
arr1 = np.arange(10)
print(arr1)
arr1= arr1+5
print(arr1)
print("Multiply",arr1*5)
print("subtraction",arr1-5) ## note: this all operation create a different array and do not change the original array
print("division",arr1/5)
print("exponent",arr1**2)


# array with array
x= np.arange(10)
y= np.arange(11,21)
print("x:",x)
print("y",y)
          # note: for this operation the length of both
          #       arrays should be same
z= x+y
print("sum of array x and y ", z)
print("product:",x*y)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
Multiply [25 30 35 40 45 50 55 60 65 70]
subtraction [0 1 2 3 4 5 6 7 8 9]
division [1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]
exponent [ 25  36  49  64  81 100 121 144 169 196]
x: [0 1 2 3 4 5 6 7 8 9]
y [11 12 13 14 15 16 17 18 19 20]
sum of array x and y  [11 13 15 17 19 21 23 25 27 29]
product: [  0  12  26  42  60  80 102 126 152 180]


In [20]:
#other cases of array with array operations
x = np.arange(6).reshape(2,3)
y = np.arange(3).reshape(1,3)
print("x:",x)
print()
print("y:",y) # since this has different shape but it does not give error this happens due to broadcasting
              # the boradcasting tries to make the arrays of the same shape but even after trying it doesnt
              # have same shape it gives error
print()
print("x+y",x+y)

x: [[0 1 2]
 [3 4 5]]

y: [[0 1 2]]

x+y [[0 2 4]
 [3 5 7]]


In [21]:
#comparison operators - boolean arrays
x = np.arange(5)
y= np.arange(1,6)
print(x)
print(y)
print(x==y)
print(x>y)
print(x<y)
print(x!=y)

[0 1 2 3 4]
[1 2 3 4 5]
[False False False False False]
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]


In [39]:
## np.random.seed() +  np.random.rand()
np.random.seed(4)
print(np.random.rand(5)) #it generates random values between  0(included) to 1(exculded)

# so the thing is random.rand gives us random values between 0 to 1
# but when we use seed() it does give random.rand() does give random value
# but it gives uniform or consistent value meaning  when we use see, all values
# belong to a particular complex formula. This help us  during the time of delopment
# because without seed() the values are not consistent



[0.96702984 0.54723225 0.97268436 0.71481599 0.69772882]


In [35]:
# np.random.randn()
np.random.randn(10) # it gives number in normal distribution

array([ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152,
       -1.58457724, -0.64770677,  0.59857517,  0.33225003, -1.14747663])

In [41]:
## np.random.randint(low,high,size)
np.random.randint(10,20,size=(5,3))


array([[17, 17, 17],
       [19, 18, 14],
       [12, 16, 14],
       [13, 10, 17],
       [15, 15, 19]])

In [65]:
#np.random.choice(), np.random.shuffle()
lst=[3,4,5,6,7,8,9]
np.random.choice(lst,3,replace=False)

#np.random.shuffle()
np.random.shuffle(lst)
print(lst)


[8, 4, 9, 6, 3, 7, 5]


Practice


In [74]:
np.random.seed(42)
np.random.randint(1,6,1)

array([4])

In [78]:
x = np.random.randint(10,50,12).reshape(3,4)
print(x)

[[34 36 37 25]
 [24 12 46 16]
 [30 18 48 27]]


In [86]:
# min ,max ,sum , mean , std
arr = np.arange(6).reshape(2,3)
print(arr)
print("Min",arr.min())
print("row min",arr.min(axis=1))
print("col min",arr.min(axis=0))
print()
print("Max",arr.max())
print("row max",arr.max(axis=1))
print("col max",arr.max(axis=0))
print()
print("sum of array ", arr.sum())
print("row sum",arr.sum(axis=1))
print("col sum",arr.sum(axis=0))
print()
print("mean of array ", arr.mean())
print("row mean",arr.mean(axis=1))
print("col mean",arr.mean(axis=0))
print()
print("median of array",np.median(arr))



[[0 1 2]
 [3 4 5]]
Min 0
row min [0 3]
col min [0 1 2]

Max 5
row max [2 5]
col max [3 4 5]

sum of array  15
row sum [ 3 12]
col sum [3 5 7]

mean of array  2.5
row mean [1. 4.]
col mean [1.5 2.5 3.5]

median of array 2.5
