NUMPY Array


In [2]:
import numpy as np

Creating an Array

In [15]:
x = np.array([2,3,4,5])
x2 = np.array([[2,3],[3,4],[5,6]])
print(x)
print(x2)
print(type(x))

[2 3 4 5]
[[2 3]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>


In [20]:
#np.zeros ,np.ones(), np.full()
print(np.zeros(20))
print(np.zeros(10,dtype='int32'))
#we can also create 2d array using dimensions
print(np.zeros((3,4),dtype='int32')) #this creates a matrix of dimension 3 by 4

print(np.full((4,3),15)) # it fill the value 15 in the area of 4 by 3



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]]


In [26]:
#np.arrange(start,stop,step)

print(np.arange(10,5,-2))

print(np.arange(10))

#np.reshape(dimensions)
print(np.arange(1,11).reshape(5,2))


[10  8  6]
[0 1 2 3 4 5 6 7 8 9]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [28]:
#np.linespace(start,stop,num)
print(np.linspace(1,10,5)) # in this it divides 1 to 10 in 5 equal parts


[ 1.    3.25  5.5   7.75 10.  ]


In [31]:
#np.eye(n)
print(np.eye(4))# it createss an identity matrix of dimensions 4 by 4
print()
print(np.eye(3,4,k=2))# this creates idetity matrix of dimensions 3 by 4 and when the 3rd parameter is given like here k=2 it will start from index 2


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [33]:
#.shape , n.dim ,.size , .dtype
x= np.arange(20).reshape(4,5)
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)

(4, 5)
2
20
int64


Practise


In [34]:
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [39]:
x=np.zeros(9).reshape(3,3)
print(x)
print()
x=np.ones(9).reshape(3,3)
print(x)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [41]:
x = np.arange(2,22,2)
print(x)

[ 2  4  6  8 10 12 14 16 18 20]


In [42]:
#slicing - +ive and -ive
arr  = np.arange(10)
print(arr)
print(arr[-3:-12:-2])


[0 1 2 3 4 5 6 7 8 9]
[7 5 3 1]


In [58]:
#slicing - submatrix (block-2D)
arr = np.arange(20).reshape(5,4)
print(arr)
print()
print(arr[2:,1:])
print()
print(arr[::4,::3])
print()
print(arr[1:3,2::-1])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[ 9 10 11]
 [13 14 15]
 [17 18 19]]

[[ 0  3]
 [16 19]]

[[ 6  5  4]
 [10  9  8]]
