In [1]:
print("hello")

hello


In [2]:
! pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 5.1 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [2]:
import numpy as np


In [3]:
x = np.arange(5)
print(x)


[0 1 2 3 4]


In [7]:
marks = np.array([92,61,45,78,33,55])
print(np.where(marks>75,"A",np.where((marks>=50) & (marks<=75),"B","C")))

['A' 'B' 'C' 'A' 'C' 'B']


In [8]:
marks = np.array([92,61,45,78,33,55])
idx = np.where(marks > 50)[0]
print("raw return:",idx)

raw return: [0 1 3 5]


In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a * b  :",a*b)
print("np.dot :",np.dot(a,b))
print("a @ b  :",a@b)

a * b  : [ 4 10 18]
np.dot : 32
a @ b  : 32


In [14]:
x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([[3,5],[5,6],[7,8]])
print(x)
print(x.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [15]:
x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([[3,5],[5,6],[7,8]])

print(x@x.T)

[[14 32]
 [32 77]]


In [40]:
s1 = [72,85,60,91]
s2 = [45,30,98,55]
s3 = [88,66,74,100]
f = np.array((s1,s2,s3))
old = np.array([['62','71','55','80'],
                ['49','58','66','73']])
print("no of student",f.shape[0])
print("no of subjects",f.shape[1])
print("total no of marks entries ",np.size(f))
print("total sum ",np.sum(f))
print(f.astype('float32'))
old = old.astype("int32")
print("converted into int ",old)
f = np.vstack((f,old))
print("combined both array",f)


no of student 3
no of subjects 4
total no of marks entries  12
total sum  864
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
converted into int  [[62 71 55 80]
 [49 58 66 73]]
combined both array [[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]


In [61]:
sheet = np.zeros((6,4),dtype='int32')
tem = np.full((6,4),35)
arr = np.arange(101,130,2)
print(arr)
arr1 = np.linspace(0,3,7)
print(arr1)
arr2 = np.eye(5)*10
print(arr2)
arr3 = np.full((4,4),35,dtype='int32')
arr4 = np.eye(4,dtype='int32')*65
print(arr3+arr4)

[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]


In [9]:
present = np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23])

print("first index:", present[0], "last index:", present[-1])
print()
print("alternate students:", present[1::2])
print()
print("last four values:", present[-4:])
print()
print("every third value after reversing:", present[::-1][::3])
print()
present[4:6] = 30
print("after changing middle students:", present)
print()
present = np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23])
print("difference between first and second half:", present[:5] - present[5:])
print()
print("top three values after reversing:", present[::-1][:3])

first index: 22 last index: 23

alternate students: [18 12 24 21 23]

last four values: [ 9 21 17 23]

every third value after reversing: [23  9 12 22]

after changing middle students: [22 18 25 12 30 30  9 21 17 23]

difference between first and second half: [-2  9  4 -5 -3]

top three values after reversing: [23 17 21]


In [10]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40],
                  [30, 48, 62, 70]])

print("Physics and Chemistry marks of middle three students:")
print(marks[1:4, 1:3])
print()
print("last subject marks:")
print(marks[:, -1])
print()
print("first and last subject of every student:")
print(marks[:, [0, -1]])
print()
print("mark sheet in reverse order:")
print(marks[::-1])
print()
marks[:, 2] = marks[:, 2] + 5
print("after increasing Chemistry marks by 5:")
print(marks)
print()
print("last row and second-last column:")
print(marks[-1, -2])
print()
print("last two students and first two subjects:")
print(marks[-2:, :2])

Physics and Chemistry marks of middle three students:
[[30 98]
 [66 74]
 [92 55]]

last subject marks:
[ 91  55 100  40  70]

first and last subject of every student:
[[ 72  91]
 [ 45  55]
 [ 88 100]
 [ 95  40]
 [ 30  70]]

mark sheet in reverse order:
[[ 30  48  62  70]
 [ 95  92  55  40]
 [ 88  66  74 100]
 [ 45  30  98  55]
 [ 72  85  60  91]]

after increasing Chemistry marks by 5:
[[ 72  85  65  91]
 [ 45  30 103  55]
 [ 88  66  79 100]
 [ 95  92  60  40]
 [ 30  48  67  70]]

last row and second-last column:
67

last two students and first two subjects:
[[95 92]
 [30 48]]


In [11]:
totals = np.array([245, 310, 178, 392, 140, 265, 199, 155, 288, 132])

print("students above 250:", totals[totals > 250])
print()
print("students above 180 and below 250:", totals[(totals > 180) & (totals < 250)])
print()
print("students below 150 or above 380:", totals[(totals < 150) | (totals > 380)])
print()
print("number of students in task 2:", np.sum((totals > 180) & (totals < 250)))
print()
print("average of students above 200:", np.mean(totals[totals > 200]))
print()
print("index positions of students below 200:", np.where(totals < 200))
print()
print("highest total among students who did not make task 1:", np.max(totals[totals <= 250]))

students above 250: [310 392 265 288]

students above 180 and below 250: [245 199]

students below 150 or above 380: [392 140 132]

number of students in task 2: 2

average of students above 200: 300.0

index positions of students below 200: (array([2, 4, 6, 7, 9]),)

highest total among students who did not make task 1: 245


In [12]:
marks = np.array([40, 55, 62, 88, 95, 33, 71, 58])

marks = np.round(marks * 1.15, 2)
print("marks after 15% increase:", marks)
print()
marks = np.minimum(marks, 100)
print("corrected marks:", marks)
print()
print("students gained less than 10 marks:", np.sum(marks - np.array([40, 55, 62, 88, 95, 33, 71, 58]) < 10))
print()
original = np.array([40, 55, 62, 88, 95, 33, 71, 58])
print("students failing before:", np.sum(original < 40))
print("students failing after:", np.sum(marks < 40))
print()
print("percentage of topper marks:", np.round(original / np.max(original) * 100, 1))
print()
print("total marks given in revaluation:", np.sum(marks - original))

marks after 15% increase: [ 46.    63.25  71.3  101.2  109.25  37.95  81.65  66.7 ]

corrected marks: [ 46.    63.25  71.3  100.   100.    37.95  81.65  66.7 ]

students gained less than 10 marks: 6

students failing before: 1
students failing after: 1

percentage of topper marks: [ 42.1  57.9  65.3  92.6 100.   34.7  74.7  61.1]

total marks given in revaluation: 64.85000000000001


In [13]:
marks = np.array([72, 45, 88, 95, 30, 67, 91, 54, 78, 39])

print("class average:", np.mean(marks))
print("middle value:", np.median(marks))
print()
print("gap between highest and lowest:", np.max(marks) - np.min(marks))
print()
print("index of topper:", np.argmax(marks))
print("index of weakest student:", np.argmin(marks))
print()
sorted_marks = np.sort(marks)
print("second highest marks:", sorted_marks[-2])
print()
print("students above class average:", np.sum(marks > np.mean(marks)))
print()
average = np.mean(marks)
std = np.std(marks)
print("students within one standard deviation:", np.sum((marks >= average - std) & (marks <= average + std)))
print()
print("class average after removing topper:", np.mean(marks[marks != np.max(marks)]))

class average: 65.9
middle value: 69.5

gap between highest and lowest: 65

index of topper: 3
index of weakest student: 4

second highest marks: 91

students above class average: 6

students within one standard deviation: 5

class average after removing topper: 62.666666666666664


In [14]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40],
                  [30, 48, 62, 70]])

print("average of each subject:", np.mean(marks, axis=0))
print("total of each student:", np.sum(marks, axis=1))
print()
print("index of toughest subject:", np.argmin(np.mean(marks, axis=0)))
print()
print("index of student who topped overall:", np.argmax(np.sum(marks, axis=1)))
print()
print("marks of student who topped each subject:", marks[np.argmax(marks, axis=0), np.arange(marks.shape[1])])
print()
print("students scoring above 60 in each subject:", np.sum(marks > 60, axis=0))
print()
print("index of subject with most spread:", np.argmax(np.std(marks, axis=0)))
print()
student = np.argmin(marks[:, 2])
print("total marks of student with lowest Chemistry:", np.sum(marks[student]))

average of each subject: [66.  64.2 69.8 71.2]
total of each student: [308 228 328 282 210]

index of toughest subject: 1

index of student who topped overall: 2

marks of student who topped each subject: [ 95  92  98 100]

students scoring above 60 in each subject: [3 3 3 3]

index of subject with most spread: 0

total marks of student with lowest Chemistry: 282


In [15]:
participants = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

np.random.seed(42)
print("three winners:", np.random.choice(participants, 3, replace=False))
print()
np.random.seed(42)
attendance = np.random.randint(60, 101, 10)
print("attendance percentages:", attendance)
print()
np.random.seed(42)
table = np.random.rand(4, 3)
table = np.round(table * 100)
print("random marks table:")
print(table)
print()
np.random.seed(42)
shuffled = np.random.permutation(participants)
print("shuffled participants:", shuffled)
print("first four participants:", shuffled[:4])
print()
np.random.seed(42)
rolls = np.random.randint(1, 7, 20)
print("number of times 6 appeared:", np.sum(rolls == 6))
print()
print("participants who crossed 80:", participants[attendance > 80])

three winners: [109 102 106]

attendance percentages: [98 88 74 67 80 98 78 82 70 70]

random marks table:
[[37. 95. 73.]
 [60. 16. 16.]
 [ 6. 87. 60.]
 [71.  2. 97.]]

shuffled participants: [109 102 106 101 108 103 110 105 104 107]
first four participants: [109 102 106 101]

number of times 6 appeared: 3

participants who crossed 80: [101 102 106 108]


In [16]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40]])

grace = np.array([5, 0, 8, 3])
weightage = np.array([1.2, 1.0, 1.1, 1.0])

marks = np.minimum(marks + grace, 100)
print("marks after grace:", marks)
print()
weighted = np.round(marks * weightage, 1)
print("weighted marks:", weighted)
print()
average = np.mean(marks, axis=0)
print("difference from subject average:", marks - average)
print()
bonus = np.array([5, 0, 2, 0])
print("marks after bonus:", np.array([[72, 85, 60, 91],
                                      [45, 30, 98, 55],
                                      [88, 66, 74, 100],
                                      [95, 92, 55, 40]]) + bonus)
print()
print("entries below subject average:", np.sum((marks - average) < 0, axis=0))
print()
spread = np.std(marks, axis=0)
print("standardized marks:", np.round((marks - average) / spread, 2))

marks after grace: [[ 77  85  68  94]
 [ 50  30 100  58]
 [ 93  66  82 100]
 [100  92  63  43]]

weighted marks: [[ 92.4  85.   74.8  94. ]
 [ 60.   30.  110.   58. ]
 [111.6  66.   90.2 100. ]
 [120.   92.   69.3  43. ]]

difference from subject average: [[ -3.    16.75 -10.25  20.25]
 [-30.   -38.25  21.75 -15.75]
 [ 13.    -2.25   3.75  26.25]
 [ 20.    23.75 -15.25 -30.75]]

marks after bonus: [[ 77  85  62  91]
 [ 50  30 100  55]
 [ 93  66  76 100]
 [100  92  57  40]]

entries below subject average: [2 2 2 2]

standardized marks: [[-0.16  0.7  -0.71  0.85]
 [-1.56 -1.59  1.51 -0.66]
 [ 0.68 -0.09  0.26  1.1 ]
 [ 1.04  0.99 -1.06 -1.28]]


In [17]:
metres = np.array([200, 500, 900, 100, 700])
sanskrit = np.array([65, 70, 88, 92, 54])

distance = np.abs(metres[:, np.newaxis] - metres)
print("distance table:")
print(distance)
print()
print("farthest distance from each block:", np.max(distance, axis=1))
print()
distance[0, 0] = np.max(distance[0])
print("nearest block to block 0:", np.argmin(distance[0]))
print()
distance = np.abs(metres[:, np.newaxis] - metres)
distance[distance == 0] = np.max(distance)
print("closest blocks:", np.where(distance == np.min(distance)))
print()
roll_numbers = np.arange(1, 25).reshape(-1, 6)
print("roll numbers:")
print(roll_numbers)
print()
print("sanskrit as column using reshape:")
print(sanskrit.reshape(-1, 1))
print()
print("sanskrit as column using newaxis:")
print(sanskrit[:, np.newaxis])
print()
print("sanskrit as single row:")
print(sanskrit.reshape(1, 5))

distance table:
[[  0 300 700 100 500]
 [300   0 400 400 200]
 [700 400   0 800 200]
 [100 400 800   0 600]
 [500 200 200 600   0]]

farthest distance from each block: [700 400 800 800 600]

nearest block to block 0: 3

closest blocks: (array([0, 3]), array([3, 0]))

roll numbers:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

sanskrit as column using reshape:
[[65]
 [70]
 [88]
 [92]
 [54]]

sanskrit as column using newaxis:
[[65]
 [70]
 [88]
 [92]
 [54]]

sanskrit as single row:
[[65 70 88 92 54]]


In [18]:
master = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

flat = master.flatten()
flat[0] = 999
print("master after task 1:")
print(master)
print()
flat = master.ravel()
flat[-1] = 111
print("master after task 2:")
print(master)
print()
middle = master.copy()
middle[1] = 0
print("master after task 3:")
print(master)
print()
double = master.copy()
double[:, :2] = double[:, :2] * 2
print("master after task 4:")
print(master)
print()
master[:, :2] = master[:, :2] * 2
print("master after task 5:")
print(master)
print()
result = master.copy()
result[result > 50] = result[result > 50] - 10
print("master after task 6:")
print(master)
print("copy after reducing values above 50:")
print(result)

master after task 1:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

master after task 2:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80 111]]

master after task 3:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80 111]]

master after task 4:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80 111]]

master after task 5:
[[ 20  40  30]
 [ 80 100  60]
 [140 160 111]]

master after task 6:
[[ 20  40  30]
 [ 80 100  60]
 [140 160 111]]
copy after reducing values above 50:
[[ 20  40  30]
 [ 70  90  50]
 [130 150 101]]


In [19]:
sec_A = np.array([[72, 85, 60],
                  [45, 30, 98],
                  [88, 66, 74]])

sec_B = np.array([[95, 92, 55],
                  [30, 48, 62]])

roll_C = np.array([201, 202, 203, 204])
marks_C = np.array([67, 82, 45, 91])
combined = np.vstack((sec_A, sec_B))

print("combined mark sheet:")
print(combined)
print("shape:", combined.shape)
print()
totals = np.sum(combined, axis=1)
combined_totals = np.hstack((combined, totals[:, np.newaxis]))
print("mark sheet with totals:")
print(combined_totals)
print()
roll_marks = np.hstack((roll_C[:, np.newaxis], marks_C[:, np.newaxis]))
print("roll numbers and marks:")
print(roll_marks)
print()
new_student = np.array([[205, 73]])
roll_marks = np.vstack((roll_marks, new_student))
print("after adding new student:")
print(roll_marks)
print()
serial = np.arange(1, 6)
serial = serial[:, np.newaxis]
combined_serial = np.hstack((serial, combined))
print("combined mark sheet with serial numbers:")
print(combined_serial)
print()
totals = np.sum(combined, axis=1)
above_200 = combined[totals > 200]
print("students whose total is above 200:")
print(above_200)
print()
grades = np.where(totals >= 225, "A",
                 np.where(totals >= 150, "B", "C"))
result = np.hstack((combined.astype(str), grades[:, np.newaxis]))
print("mark sheet with grades:")
print(result)

combined mark sheet:
[[72 85 60]
 [45 30 98]
 [88 66 74]
 [95 92 55]
 [30 48 62]]
shape: (5, 3)

mark sheet with totals:
[[ 72  85  60 217]
 [ 45  30  98 173]
 [ 88  66  74 228]
 [ 95  92  55 242]
 [ 30  48  62 140]]

roll numbers and marks:
[[201  67]
 [202  82]
 [203  45]
 [204  91]]

after adding new student:
[[201  67]
 [202  82]
 [203  45]
 [204  91]
 [205  73]]

combined mark sheet with serial numbers:
[[ 1 72 85 60]
 [ 2 45 30 98]
 [ 3 88 66 74]
 [ 4 95 92 55]
 [ 5 30 48 62]]

students whose total is above 200:
[[72 85 60]
 [88 66 74]
 [95 92 55]]

mark sheet with grades:
[['72' '85' '60' 'B']
 ['45' '30' '98' 'B']
 ['88' '66' '74' 'A']
 ['95' '92' '55' 'A']
 ['30' '48' '62' 'C']]
